import type { ProductAnalyticsRecord } from "./analytics";

// Custom environment variable declarations that augment the auto-generated Cloudflare.Env.
// (worker-configuration.d.ts is auto-generated by `wrangler types` and should not be edited.)

declare global {
  namespace Cloudflare {
    interface Env {
      // Deployment-wide admin usernames: a JSON binding, or the same array as a JSON string
      // (which is what a secret binding, can carry).
      ADMINS?: string[] | string;

      // Workers AI binding (injected by generate-wrangler-prod / run-dev-server; not in base wrangler.jsonc).
      WORKERS_AI: Ai;

      // AI Gateway mode: when CF_AI_GATEWAY is set, supported providers are routed through
      // Cloudflare AI Gateway with server-managed keys. Users don't need their own keys.
      CF_AI_GATEWAY?: string;            // Gateway name (enables gateway mode)
      CF_AI_GATEWAY_PROVIDERS?: string;   // Comma-separated list: "anthropic,openai,google,cloudflare"
      CF_AI_GATEWAY_ACCOUNT_ID?: string;  // Gateway owner account ID (required with CF_AI_GATEWAY)
      CF_AI_GATEWAY_API_TOKEN?: string;   // Run + Read token; optional when the binding transport
                                          // applies (still required for google)
      CF_AI_GATEWAY_USE_BINDING?: string;
      // Note: outside gateway mode, Workers AI (provider "cloudflare") is BYOK like every other
      // provider -- the account ID and API token live in the user's model config, not in env.

      // Direct deployment-managed catalog (nonsecret JSON); omitted/[] disables it.
      SHARED_AI_MODELS?: { model: string; name: string }[] | string;
      // Workshop-only Worker secret. Never copied to User DOs or public configuration.
      CLIPROXY_API_KEY?: string;

      // Blueprint storage bindings.
      BLUEPRINTS: KVNamespace;             // Workers KV for blueprint metadata lookup
      BLUEPRINT_CONTENT: R2Bucket;         // R2 bucket for blueprint code snapshots

      // User avatar storage.
      AVATARS: KVNamespace;                // Workers KV for user avatar images

      // Note: gatekeeper service bindings (GATEKEEPER_*) are intentionally NOT declared here. Core
      // discovers them generically by scanning env for the GATEKEEPER_ prefix (buildGatekeeperVendorMap)
      // and never references a specific gatekeeper by name, so naming one here would be wrong.

      // Optional product analytics stream. Deployments can bind this to a
      // structured Cloudflare Pipelines stream; local/dev configs omit it and analytics no-op.
      PRODUCT_ANALYTICS?: import("cloudflare:pipelines").Pipeline<ProductAnalyticsRecord>;

      // Optional browser error pipeline. Both bindings must be present before reports dispatch.
      FRONTEND_ERROR_REPORTER?: Service<
        import("@gadgets/observability/error-reporting").ErrorReporter
      >;
      FRONTEND_ERROR_RATE_LIMITER?: RateLimit;

      // The Browser Run binding (BROWSER) used to render Gadget exports is intentionally NOT
      // redeclared here: wrangler's generated types make it required, and TypeScript 7 rejects
      // weakening it to optional in a merged augmentation. Self-hosted deployments may omit the
      // binding, so use sites read it as `BrowserRun | undefined` and null-check.

      // ---------------------------------------------------------------------------------------------
      // Optional features: sign-in via authentication gatekeepers + AI Gateway billing (free-tier
      // limits / top-up). All OFF by default; existing password / Cloudflare Access deployments are
      // unaffected. OAuth app credentials live on the gatekeeper Workers, not here.
      // ---------------------------------------------------------------------------------------------

      // Cloudflare Access configuration. When CF_ACCESS_AUD is set, the deployment authenticates via
      // Cloudflare Access (SSO). (Also referenced via a local Env extension in server.ts.)
      CF_ACCESS_AUD?: string;   // audience
      CF_ACCESS_ISS?: string;   // team URL, e.g. https://<team>.cloudflareaccess.com

      // Comma-separated allowlist of gatekeeper vendor ids permitted to drive sign-in (e.g.
      // "google,github,cloudflare"). A listed gatekeeper must also advertise providesAuth. Empty =
      // no gatekeeper sign-in (password / CF Access only).
      AUTH_GATEKEEPERS?: string;

      // Set to "true" to disable username/password login + signup (gatekeeper sign-in only). Only
      // takes effect when at least one auth gatekeeper is allowlisted (otherwise password auth stays
      // on to avoid locking everyone out).
      DISABLE_PASSWORD_AUTH?: string;

      // Enables the Cloudflare free-tier limits + top-up flow when set to "true".
      ENABLE_CLOUDFLARE_LIMITS?: string;

      // Public base URL of the deployment.
      PUBLIC_BASE_URL?: string;

      // Daily free-tier LLM-call limit (per user). Defaults to DEFAULT_DAILY_LLM_CALL_LIMIT.
      DAILY_LLM_CALL_LIMIT?: string;

      // Minimum connected-account balance (USD) to proceed via BYOK. Defaults to
      // MINIMUM_CLOUDFLARE_BALANCE.
      MINIMUM_CLOUDFLARE_BALANCE?: string;
    }
  }
}
