#!/usr/bin/env node
/**
 * Regenerate worker-configuration.d.ts for every package that has wrangler.jsonc.
 *
 * Post-processing (so we don't hand-edit the giant generated file):
 * 1. Point mainModule at ./src/* instead of gitignored .wrangler/validate/*
 * 2. If src/env.d.ts owns GlobalProps, drop the generated project header
 *    (runtime types only) so the two don't fight.
 * 3. workshop-backend, gatekeeper-google: keep the manual `restore` export until wrangler emits it.
 * 4. Normalize the "Generated by Wrangler" banner (path args differ for --check).
 *
 * Project-specific secrets/vars belong in src/env.d.ts (or a local `type Env =
 * Cloudflare.Env & { ... }`), not in the generated file.
 *
 * `--check` is non-mutating: writes a sibling temp file, compares, deletes it.
 */
import { spawnSync } from "node:child_process";
import { readdir, readFile, rm, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveBinEntry } from "./bin-entry.ts";
import { pnpmCommand } from "./pnpm-command.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packagesDir = join(root, "packages");
const checkOnly = process.argv.includes("--check");
const CHECK_BASENAME = "worker-configuration.check.d.ts";
const runtimeOnlyConfigs = new Map([
  [join(packagesDir, "mcp-shared"), join(packagesDir, "gatekeeper-mcp", "wrangler.jsonc")],
]);

const RESTORE_PATCH = `

    // TODO: Fix bug in runtime types where this isn't declared in the types. It is actually
    // exported by the runtime.
    export const restore: symbol;
`;

async function packageDirs(): Promise<string[]> {
  const names = await readdir(packagesDir, { withFileTypes: true });
  const out: string[] = [];
  for (const ent of names) {
    if (!ent.isDirectory()) continue;
    const dir = join(packagesDir, ent.name);
    try {
      await readFile(join(dir, "wrangler.jsonc"));
      out.push(dir);
    } catch {
      // no wrangler.jsonc
    }
  }
  out.push(...runtimeOnlyConfigs.keys());
  return out.toSorted();
}

async function ownsGlobalProps(pkgDir: string): Promise<boolean> {
  try {
    const text = await readFile(join(pkgDir, "src", "env.d.ts"), "utf8");
    return /\binterface\s+GlobalProps\b/.test(text);
  } catch {
    return false;
  }
}

function rewriteMainModule(text: string): string {
  return text.replace(
    /mainModule:\s*typeof import\("\.\/\.wrangler\/validate\/src\/([^"]+)"\)/g,
    'mainModule: typeof import("./src/$1")',
  );
}

function stripProjectHeader(text: string): string {
  const begin = text.indexOf("// Begin runtime types");
  if (begin < 0) return text;
  const workerd = text.match(/\/\/ Runtime types generated with workerd@[^\n]+/)?.[0]
    ?? "// Runtime types generated with workerd";
  return `/* eslint-disable */\n${workerd}\n${text.slice(begin)}`;
}

function ensureRestoreExport(text: string): string {
  // Drop any prior restore patch so re-generation is idempotent (blank-line drift, etc.).
  text = text.replace(
    /\n(?:\s*\n)?\s*\/\/ TODO: Fix bug in runtime types where this isn't declared[\s\S]*?export const restore: symbol;\n/,
    "\n",
  );
  // Insert before the closing brace of CloudflareWorkersModule (the one right before
  // `declare module \'cloudflare:workers\'`).
  const marker = /export const tracing: Tracing;\n\}/;
  if (!marker.test(text)) {
    throw new Error("could not find CloudflareWorkersModule closing (tracing export) to patch restore");
  }
  return text.replace(marker, `export const tracing: Tracing;${RESTORE_PATCH}}`);
}

/** Drop path args from the banner so check/gen compare equal. */
function normalizeBanner(text: string): string {
  return text.replace(
    /^\/\/ Generated by Wrangler by running `wrangler types[^`]*`/m,
    "// Generated by Wrangler by running `wrangler types`",
  );
}

async function postprocess(pkgDir: string, text: string): Promise<string> {
  let next = normalizeBanner(text);
  next = rewriteMainModule(next);
  if (await ownsGlobalProps(pkgDir)) {
    next = stripProjectHeader(next);
  }
  if (["workshop-backend", "gatekeeper-google"].includes(basename(pkgDir))) {
    next = ensureRestoreExport(next);
  }
  return next.replace(/[ \t]+$/gm, "");
}

async function generateOne(pkgDir: string): Promise<void> {
  const rel = relative(root, pkgDir);
  const typesPath = join(pkgDir, "worker-configuration.d.ts");
  const before = checkOnly ? await readFile(typesPath, "utf8").catch(() => null) : null;

  // Keep output under the package so mainModule paths match generate mode.
  // --check uses a sibling temp name and never touches worker-configuration.d.ts.
  const outPath = checkOnly ? join(pkgDir, CHECK_BASENAME) : typesPath;

  try {
    const runtimeOnlyConfig = runtimeOnlyConfigs.get(pkgDir);
    const args = ["types", outPath];
    if (runtimeOnlyConfig) {
      args.push("--config", runtimeOnlyConfig, "--include-env", "false");
    }
    // Reached directly where wrangler resolves, which also avoids `pnpm exec` being unspawnable on
    // Windows; packages without their own copy (mcp-shared) fall back through pnpm-command.ts.
    const wranglerEntry = resolveBinEntry(pkgDir, "wrangler");
    const [command, argv]: [string, string[]] = wranglerEntry
      ? [process.execPath, [wranglerEntry, ...args]]
      : pnpmCommand(["exec", "wrangler", ...args]);
    const result = spawnSync(
      command,
      argv,
      { cwd: pkgDir, encoding: "utf8", env: process.env },
    );
    // A failure to spawn leaves `status` null with no output, which the check below would report as
    // a wrangler failure with two blank lines. Surface the real cause instead.
    if (result.error) {
      throw new Error(`could not run wrangler in ${rel}: ${result.error.message}`);
    }
    if (result.status !== 0) {
      console.error(result.stdout);
      console.error(result.stderr);
      throw new Error(`wrangler types failed in ${rel}`);
    }

    const raw = await readFile(outPath, "utf8");
    const next = await postprocess(pkgDir, raw);

    if (checkOnly) {
      if (before === null || before !== next) {
        throw new Error(`${rel}/worker-configuration.d.ts is out of date (run pnpm types:generate)`);
      }
      console.log(`ok  ${rel}`);
      return;
    }

    if (next !== raw) {
      await writeFile(typesPath, next);
    }
    console.log(`gen ${rel}`);
  } finally {
    if (checkOnly) {
      await rm(outPath, { force: true });
    }
  }
}

const dirs = await packageDirs();
if (dirs.length === 0) {
  console.error("no packages with wrangler.jsonc found");
  process.exit(1);
}

let failed = 0;
for (const dir of dirs) {
  try {
    await generateOne(dir);
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    failed++;
  }
}
if (failed) process.exit(1);
